/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:f6de052a-e60f-495c-8e4e-8ed095f8410f",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_H62wNvsfv",
    "aws_user_pools_web_client_id": "3l7gqvpgc9d100r4mhu5re62b6",
    "oauth": {}
};


export default awsmobile;
